title: Your awesome title
author: GitHub User
email: myemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is all about the beneficial plants on my homestead.
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: mytwitterhandle
github_username:  cjoliva

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
